name: Build Windows EXE

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows --release

      # نسخ ملف الـ DLL المطلوبة إلى مجلد الـ Release تلقائياً
      - name: Copy VC++ Runtime DLLs
        run: |
          cp "C:\Windows\System32\vcruntime140_1.dll" "build\windows\runner\Release\" -ErrorAction SilentlyContinue

      - uses: actions/upload-artifact@v3
        with:
          name: Windows-EXE
          path: build/windows/runner/Release/
